### PR TITLE
Removed numbered guide and callouts view modes

### PR DESCRIPTION
**Pull request by sherakama**
Removed all references to callout and numbered guides.

### CODE REVIEW

**Comment by sherakama** [comment]
Please test to see if the rest of the module still works and looks right :)

**Comment by jbickar** [comment]
There are a couple of bugs, probably not related to this PR (and one may not be a bug):
1. In the "Cards" view mode, landing page items without link fields still act as hyperlinks
2. When you create a landing page (field collection) item, and browse for an image to upload, but click "Add another item" before clicking "upload", the image gets lost (this might be a limitation in Drupal and the FAPI).

I'll do a final checky on this tomorrow and merge.

**Comment by jbickar** [comment]
Oh and we only have one Behat test for landing page, in `jsa/features/site_owner.feature`, and it's not very comprehensive.

**Comment by jbickar** [comment]
Thanks for this.

**Comment by sherakama** [comment]
Great! yeah. We need moar tests. I think `/includes/features` may have something better or `/jsplus/features`

**Pull request merged**
