### PR TITLE
BASIC-2027: Fix up column class for titles

### PR DESCRIPTION
**Pull request by sherakama**
Adds column class to title to keep card size consistent.
Please see Jira ticket for more information.

### CODE REVIEW

**Comment by sherakama** [comment]
@nickmanning, FYI.

**Comment by jbickar** [comment]
No assigning pull requests on weekends; that's dirty pool.

On May 14, 2016, at 14:33, Sherakama <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #17https://github.com/SU-SWS/stanford_landing_page/pull/17 to @jbickarhttps://github.com/jbickar.

##

**Comment by sherakama** [comment]
This PR is to add the column class to the output so that titles all align instead of wonky heights. The other thing this fixes is the missing CSS class of the view mode itself. It is not being used but I guess was intended to but never did work... until now.

**Comment by jbickar** [comment]
Where/how can I test this? I'm fine with just looking at it on a dev site and toggling branches back and forth.

**Comment by sherakama** [comment]
Create a landing page with 3 landing page items. One with a short title, one with a medium title, and one with a very long title. 

Check to see that they align and that the column class is there.

**Comment by jbickar** [comment]
2016-06-03-123531-screenshot

**Comment by jbickar** [comment]
Sorry for delay. Good jorb.

**Pull request merged**
